# Generated by Django 6.0.3 on 2026-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
