from django.urls import path
from .views import (
    meal_list,
    meal_create,
    meal_update,
    meal_delete,
    meals_week_to_shopping,
    recipe_list,
    recipe_create,
    recipe_update,
    recipe_delete,
    recipe_detail,
    recipe_all_to_shopping,
    ingredient_add,
    ingredient_delete,
    ingredient_scale,
    ingredient_to_shopping,
    shopping_merge_quantity,
    recipe_ai_suggest,
    recipe_apply_suggestion,
)

urlpatterns = [
    path("", meal_list, name="meal_list"),
    path("to-shopping/", meals_week_to_shopping, name="meals_week_to_shopping"),
    path("new/", meal_create, name="meal_create"),
    path("<int:pk>/edit/", meal_update, name="meal_update"),
    path("<int:pk>/delete/", meal_delete, name="meal_delete"),

    path("recipes/", recipe_list, name="recipe_list"),
    path("recipes/new/", recipe_create, name="recipe_create"),
    path("recipes/<int:pk>/", recipe_detail, name="recipe_detail"),
    path("recipes/<int:pk>/edit/", recipe_update, name="recipe_update"),
    path("recipes/<int:pk>/delete/", recipe_delete, name="recipe_delete"),
    path("recipes/<int:pk>/ingredients/add/", ingredient_add, name="ingredient_add"),
    path("ingredients/<int:pk>/to-shopping/", ingredient_to_shopping, name="ingredient_to_shopping"),
    path("ingredients/<int:pk>/delete/", ingredient_delete, name="ingredient_delete"),
    path("ingredients/<int:pk>/scale/", ingredient_scale, name="ingredient_scale"),
    path("shopping/<int:pk>/merge/", shopping_merge_quantity, name="shopping_merge_quantity"),
    path("recipes/<int:pk>/all-to-shopping/", recipe_all_to_shopping, name="recipe_all_to_shopping"),
    path("recipes/<int:pk>/ai-suggest/", recipe_ai_suggest, name="recipe_ai_suggest"),
    path("recipes/<int:pk>/apply-suggestion/", recipe_apply_suggestion, name="recipe_apply_suggestion"),
]