# Generated by Django 6.0.3 on 2026-05-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Keine'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='none', max_length=10),
        ),
    ]
