"""
Django settings for wochi project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-only-for-local")
DEBUG = os.environ.get("DEBUG", "False") == "True"

if not DEBUG and not os.environ.get("SECRET_KEY"):
    raise ValueError("SECRET_KEY environment variable must be set in production.")

# Werte, die öffentlich im Repository stehen (oder standen). Mit einem davon
# könnte jeder Sitzungen und App-Tokens fälschen. accounts/checks.py warnt
# beim Start, statt den Start zu verweigern – ein harter Abbruch würde sonst
# ein laufendes Deployment unbemerkt lahmlegen.
KNOWN_INSECURE_SECRET_KEYS = {
    "dev-secret-key-only-for-local",
    "dev-secret-key",
    "bitte-einen-langen-zufaelligen-wert-setzen",
}

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS", "localhost,127.0.0.1"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "accounts",
    "households",
    "tasks",
    "meals",
    "shopping",
    "api",
    "timetracking",

    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wochi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wochi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de'

# Deutsche App: timezone.localdate() muss den deutschen Kalendertag liefern.
# Mit 'UTC' war zwischen 00:00 und 02:00 Ortszeit noch der Vortag aktiv.
TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Django 6 ignoriert STATICFILES_STORAGE; ohne STORAGES liefen die
# Static-Files bisher ohne Hash im Namen und ohne Kompression aus.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
# Fehlt ein Eintrag im Manifest (Tests, vergessenes collectstatic), wird der
# ungehashte Pfad ausgeliefert statt die ganze Seite mit 500 abzubrechen.
WHITENOISE_MANIFEST_STRICT = False
LOGIN_REDIRECT_URL = "home"
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL", "")
LOGOUT_REDIRECT_URL = "login"

# Anmeldung mit Benutzername oder E-Mail, unabhängig von Groß-/Kleinschreibung.
AUTHENTICATION_BACKENDS = ["accounts.backends.UsernameOrEmailBackend"]

from django.contrib.messages import constants as message_constants

# Bootstrap kennt keine Klasse "alert-error"; Fehlermeldungen waren nicht rot.
MESSAGE_TAGS = {message_constants.ERROR: "danger"}

import cloudinary
cloudinary.config(cloudinary_url=CLOUDINARY_URL)

CSRF_TRUSTED_ORIGINS = [
    "https://wochii.de",
    "https://www.wochii.de",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = "DENY"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.WochiiJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/minute",
        "user": "300/minute",
        "auth": "5/minute",
        "refresh": "30/minute",
        "password_reset": "5/hour",
        "ai": "20/hour",
    },
    # Hinter genau einem Reverse-Proxy: für die IP-basierte Drosselung zählt
    # die letzte (vom Proxy gesetzte) Adresse in X-Forwarded-For, nicht die
    # erste, die der Client frei wählen kann.
    "NUM_PROXIES": int(os.environ.get("NUM_PROXIES", "1")),
}

from datetime import timedelta
SIMPLE_JWT = {
    # Kurzlebige Access-Tokens; die App erneuert sie im Hintergrund.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    # Gleitende Anmeldung: jeder Refresh liefert ein neues Refresh-Token.
    # Wer die App regelmäßig nutzt, bleibt angemeldet; nach 60 Tagen ohne
    # Nutzung ist eine neue Anmeldung nötig. Widerruf bei Passwortwechsel:
    # siehe api/authentication.py.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "SIGNING_KEY": os.environ.get("JWT_SIGNING_KEY") or SECRET_KEY,
    "TOKEN_OBTAIN_SERIALIZER": "api.authentication.WochiiTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "api.authentication.WochiiTokenRefreshSerializer",
}

_cors_default = "http://localhost:8081,http://localhost:19006" if DEBUG else ""
_cors_extra = "https://wochii.de,https://www.wochii.de"
CORS_ALLOWED_ORIGINS = [
    o for o in (os.environ.get("CORS_ALLOWED_ORIGINS", _cors_default) + "," + _cors_extra).split(",") if o
]
CORS_ALLOW_ALL_ORIGINS = False

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@wochii.de")

# Gültigkeit der Links zum Zurücksetzen des Passworts (24 Stunden), passend
# zur Frist der E-Mail-Bestätigung im Profil.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Fehler aus logger.exception(...) landen im Container-Log (gunicorn stderr).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "WARNING"},
    # 4xx sind normale Nutzerfehler; nur echte Serverfehler (5xx) loggen.
    "loggers": {"django.request": {"level": "ERROR"}},
}
