# Generated by Django 6.0.3 on 2026-05-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0004_migrate_job_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together={('job', 'date')},
        ),
    ]
