# Generated by Django 6.0.3 on 2026-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0005_alter_workentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
