# Generated by Django 6.0.3 on 2026-04-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('produce', 'Obst & Gemüse'), ('dairy', 'Milchprodukte'), ('meat', 'Fleisch'), ('dry', 'Trockenwaren'), ('frozen', 'Tiefkühl'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('is_bought', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='households.household')),
            ],
            options={
                'ordering': ['is_bought', 'category', 'name'],
            },
        ),
    ]
