# Generated by Django 6.0.3 on 2026-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_store_shoppingsession_storeitemorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['is_bought', 'name']},
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='category',
        ),
    ]
