# Generated by Django 6.0.3 on 2026-09-23 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_householdselection'),
        ('shopping', '0004_alter_shoppingitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_key', models.CharField(max_length=200)),
                ('times_added', models.PositiveIntegerField(default=0)),
                ('last_added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-times_added', '-last_added_at'],
            },
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shoppingsession',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shoppingitem',
            constraint=models.UniqueConstraint(fields=('household', 'client_id'), name='unique_shopping_item_client_id'),
        ),
        migrations.AddConstraint(
            model_name='shoppingsession',
            constraint=models.UniqueConstraint(fields=('household', 'client_id'), name='unique_shopping_session_client_id'),
        ),
        migrations.AddField(
            model_name='frequentitem',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_items', to='households.household'),
        ),
        migrations.AddConstraint(
            model_name='frequentitem',
            constraint=models.UniqueConstraint(fields=('household', 'name_key'), name='unique_frequent_item_per_household'),
        ),
    ]
